project:
  type: website
  output-dir: docs
website:
  favicon: "content/images/logo_yellow3.png"
  site-url: https://edgarodriguez.github.io/quarto-web-testing/
  repo-url: https://github.com/edgarodriguez/quarto-web-testing
  navbar:
    pinned: true
    logo: "content/img/logo_yellow3.png"
    background: primary
    right:
      - href: about.qmd
      - href: people.qmd
      - href: publications.qmd
      - text: Resources
        menu:
          - text: Datasets
            href: resources.qmd
          - text: Literature analysis
            href: publications.qmd
          - text: Datavizs
            href: alphaxiv.qmd              
          - text: Alphaxiv
            href: alphaxiv.qmd            
      - text: Blog
        href: blog.qmd 
      - text: News/Events
        href: news.qmd
      - text: Contact
        href: contact.qmd      



  page-footer:
    background: light
    left: © Copyright 2024, Edgar Rodríguez-Huerta
    right: This website is built with {{< fa heart title="a heart" >}} and Quarto. Multi-lenguage website is possible thanks to babelquarto and Joel Nitto Web
  google-analytics: "G-RG1R3XP26Q"
  announcement:
    icon: info-circle
    dismissable: true
    content: "**Announcement** - We are working in the website. Official release will be soon / Anúncio - Estamos trabalhando no site. O lançamento oficial será em breve"
    type: success
    position: below-navbar

format:
  html:
    theme: lux
     # light: flatly
     # dark: darkly
    fontsize: 1.2rem
    #fontcolor: "#212121"
    mainfont: inter
    css: jnitta_theme.css
    include-in-header:
      - text: |
         <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
    toc: true

babelquarto:
  languagecodes:
  - name: pt
    text: "Português"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['pt']
title-pt: 
description-pt: CRVA
author-pt: Edgar Rodriguez Huerta
lang: en

# Override language specific fields here
babelquarto-pt:
  format:
    html:
      comments:
        giscus:
          language: pt
  website:
    navbar:
      right:
        - href: talks.qmd
          text: Platicas
