project:
  type: website

website:
  title: "For test from Joel Nitta (example using github repo)"
  navbar:
    background: primary
    right:
      - href: publications.qmd
      - href: software.qmd
      - href: blog.qmd
      - href: talks.qmd
      - href: teaching.qmd


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: jnitta_theme.css
    toc: true

    include-in-header: header.html

babelquarto:
  languagecodes:
  - name: pt
    text: "Port"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['pt']
title-pt: ニClimate Resilience for Workers
description-pt: ニCRVAA
author-pt: ニCRVA
lang: en

# Override language specific fields here
babelquarto-pt:
  format:
    html:
      comments:
        giscus:
          language: pt
  website:
    navbar:
      right:
        - href: talks.qmd
          text: Platicas
