project:
  type: website
  output-dir: docs

website:
  site-url: https://edgarodriguez.github.io/quarto-web-testing/
  repo-url: https://github.com/edgarodriguez/quarto-web-testing
  repo-actions: [edit, issue]
  title: "CRVA Brazil"
  open-graph: true
  navbar:
    title: false
    logo: logo.png
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: get in touch!
        menu:
          - icon: twitter
            text: Twitter
            href: https://twitter.com/edgarodriguez
            target: _blank
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/edgarodriguez
            target: _blank
          - icon: envelope
            text: email
            href: mailto:edgar.rodriguez@nottingham.ac.uk
      - icon: github
        href: https://github.com/edgarodriguez
        target: _blank
  announcement:
    icon: info-circle
    dismissable: true
    content: "**Announcement** - We are working in the website. Official release will be soon"
    type: primary
    position: below-navbar

  page-footer:
    background: light
    left: © Copyright 2024, ERH
    right: This website is built with {{< fa heart title="a heart" >}} Multi-lenguage thanks to babelquarto :)
format:
  html:
    theme: sandstone
    css: styles.css




babelquarto:
  languagecodes:
  - name: pt
    text: "Portuiguese"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['pt']
title-pt: title in pt
description-pt: description in pt
author-pt: author in pt
lang: en
