project:
  type: website
  output-dir: docs
website:

  title: "Example blog babel project multilingual"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


babelquarto:
  languagecodes:
  - name: es
    text: "Version in es"
  - name: pt
    text: "Version in portuguese"
  - name: en
    text: "Version in en"
  mainlanguage: 'en'
  languages: ['pt','es']
title-es: title in es
title-pt: title in pt
description-es: description in es
description-pt: description in pt
author-es: author in es
author-pt: author in pt
lang: en
