project:
  type: website
  output-dir: docs
website:
  favicon: "content/images/logo_test.png"
  site-url: https://edgarodriguez.github.io/quarto-web-testing/
  repo-url: https://github.com/edgarodriguez/quarto-web-testing
  title: "From amazing web Joel Nitta (example using github repo)"
  navbar:
    pinned: true
    logo: "content/images/logo_test.png"
    background: primary
    right:
      - href: about.qmd
      - href: people.qmd
      - text: Publications
        href: publications.qmd
      - text: Resources
        menu:
          - text: Datasets
            href: resources.qmd
          - text: Literature review
            href: publications.qmd
      - text: News
        href: blog.qmd
      - text: Blog
        href: blog.qmd
      - text: Contact
        menu:
          - icon: twitter
            text: Twitter
            href: https://twitter.com/edgarodriguez
            target: _blank
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/edgarodriguez
            target: _blank
          - icon: envelope
            text: email
            href: mailto:edgar.rodriguez@nottingham.ac.uk


  page-footer:
    background: light
    left: © Copyright 2024, ERH
    right: This website is built with {{< fa heart title="a heart" >}} Multi-lenguage thanks to babelquarto and Joel Nitto :)
  google-analytics: "G-RG1R3XP26Q"
  announcement:
    icon: info-circle
    dismissable: true
    content: "**Announcement** - We are working in the website. Official release will be soon"
    type: success
    position: below-navbar

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: jnitta_theme.css
    include-in-header:
      - text: |
          <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    toc: true

babelquarto:
  languagecodes:
  - name: pt
    text: "Português"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['pt']
title-pt: Climate Resilience for Workers
description-pt: CRVAA
author-pt: Edgar Rodriguez
lang: en

# Override language specific fields here
babelquarto-pt:
  format:
    html:
      comments:
        giscus:
          language: pt
  website:
    navbar:
      right:
        - href: talks.qmd
          text: Platicas
