---
title: about
sidebar: false
page-layout: article
toc: false
title-block-banner: false
lang: en
---



## What is alphaxiv?

https://www.alphaxiv.org

alphaXiv.org is an online platform designed for open and collaborative discussion on research papers published on arXiv. It allows users to leave comments directly on specific lines within a paper, fostering a more focused and insightful conversation.

## Our proposal
Our goal is abrir nuevas formas de compartir informaci칩n y aprendizaje durantes todas las etapdas del proyecto, incluyendo revisi칩n bibliografica,  elaboracion de borradores, y discusi칩n entre el equipo de trabajo.

As open-access tool, we will try to include analysis related oour literature review and process during the elboration od the methodlogical framework. 
Likewise, we believe will be a powerfool tool to collaborate with other stakeholders durii g the project

## How?

We will share links to the documents that we are using..

## Other ideas

- Intentar a침adir analisis de redes en la literatura para idnetificar key references.. Igualmente, idneitifcar missingness.
- Revisar opciones de agregar widgets de research rabbit o obsidian.

{{< ai arxiv >}} 
{{< ai google-scholar >}}
{{< ai open-access >}}
{{< ai open-access size=3x >}}

